# .github/workflows/security.yml
# 安全性檢查
name: Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run security audit
      run: npm audit
